title: Malware Writups
url: https://zoomequipd.github.io
baseurl: /malware_writeups
remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

twitter_username: zoomequipd
github_username: zoomequipd
minimal_mistakes_skin: default
search: true

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/zoomequipd"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/zoomequipd"